version: '3.8'

services:
  web:
    build: .
    command: npm run start:dev
    ports:
      - '3000:3000'
    depends_on:
      - db
    volumes:
      - ./src:/usr/src/app/src
    env_file:
      - .env

  db:
    container_name: spark-db
    image: postgres:latest
    ports:
      - '5434:5432'
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: spark
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
